import { Text } from "../components";

export function AIGeneratedBanner() {
  return (
    <blockquote style={{ marginBottom: '10px' }}>
      <Text>🤖 <b>AI-generated:</b> This doc was generated by AI and hasn&apos;t been human-edited yet.</Text>
    </blockquote>
  );
}
