import React from 'react';
import { primary, error, success, warning } from '../../../constants/colors';

export const modalVariants = {
  confirm: {
    title: 'Are you sure?',
    message: 'This action cannot be undone.',
    confirmLabel: 'OK',
    cancelLabel: 'Cancel',
    buttonVariant: 'primary',
    icon: 'fas fa-circle-question',
    iconColor: primary[200],
    iconBackgroundColor: primary[50],
  },
  info: {
    title: 'Info',
    message: 'This action cannot be undone.',
    confirmLabel: 'OK',
    cancelLabel: 'Cancel',
    buttonVariant: 'primary',
    icon: 'fas fa-circle-info',
    iconColor: primary[200],
    iconBackgroundColor: primary[50],
  },
  success: {
    title: 'Success',
    message: 'Operation completed successfully!',
    confirmLabel: 'OK',
    cancelLabel: 'Cancel',
    buttonVariant: 'success',
    icon: 'fas fa-circle-check',
    iconColor: success[200],
    iconBackgroundColor: success[50],
  },
  error: {
    title: 'Oops!',
    message: 'An error occurred and your changes were not saved. Please try again.',
    confirmLabel: 'OK',
    cancelLabel: 'Cancel',
    buttonVariant: 'cancel',
    icon: 'fas fa-circle-exclamation',
    iconColor: error[100],
    iconBackgroundColor: error[50],
  },
  warning: {
    title: 'Warning',
    message: 'This action cannot be undone. Are you sure?',
    confirmLabel: 'Yes, proceed',
    cancelLabel: 'Cancel',
    buttonVariant: 'warning',
    icon: 'fas fa-triangle-exclamation',
    iconColor: warning[100],
    iconBackgroundColor: warning[50],
  },
  cancel: {
    title: 'Delete Item',
    message: 'Are you sure you want to delete this item? This action cannot be undone.',
    confirmLabel: 'Delete',
    cancelLabel: 'Cancel',
    buttonVariant: 'cancel',
    icon: 'fas fa-trash-can',
    iconColor: error[100],
    iconBackgroundColor: error[50],
  },
} as const;
