import React from 'react';
import { error, primary, success, warning } from '../../../constants/colors';

export const modalVariants = {
  cancel: {
    buttonVariant: 'cancel',
    cancelLabel: 'Cancel',
    confirmLabel: 'Delete',
    icon: 'fas fa-trash-can',
    iconBackgroundColor: error[25],
    iconColor: error[200],
    message:
      'Are you sure you want to delete this item? This action cannot be undone.',
    title: 'Delete Item',
  },
  confirm: {
    buttonVariant: 'primary',
    cancelLabel: 'Cancel',
    confirmLabel: 'OK',
    icon: 'fas fa-circle-question',
    iconBackgroundColor: primary[25],
    iconColor: primary[200],
    message: 'This action cannot be undone.',
    title: 'Are you sure?',
  },
  delete: {
    buttonVariant: 'cancel',
    cancelLabel: 'Cancel',
    confirmLabel: 'Delete',
    icon: 'fas fa-trash-can',
    iconBackgroundColor: error[25],
    iconColor: error[100],
    message:
      'Are you sure you want to delete this item? This action cannot be undone.',
    title: 'Delete Item',
  },
  error: {
    buttonVariant: 'cancel',
    cancelLabel: 'Cancel',
    confirmLabel: 'OK',
    icon: 'fas fa-circle-exclamation',
    iconBackgroundColor: error[25],
    iconColor: error[100],
    message:
      'An error occurred and your changes were not saved. Please try again.',
    title: 'Oops!',
  },
  info: {
    buttonVariant: 'primary',
    cancelLabel: 'Cancel',
    confirmLabel: 'OK',
    icon: 'fas fa-circle-info',
    iconBackgroundColor: primary[25],
    iconColor: primary[200],
    message: 'This action cannot be undone.',
    title: 'Info',
  },
  success: {
    buttonVariant: 'success',
    cancelLabel: 'Cancel',
    confirmLabel: 'OK',
    icon: 'fas fa-circle-check',
    iconBackgroundColor: success[25],
    iconColor: success[200],
    message: 'Operation completed successfully!',
    title: 'Success',
  },
  remove: {
    buttonVariant: 'cancel',
    cancelLabel: 'Cancel',
    confirmLabel: 'Remove',
    icon: 'fas fa-circle-minus',
    iconBackgroundColor: error[25],
    iconColor: error[100],
    message: 'This item will be removed.',
    title: 'Remove item?',
  },
  warning: {
    buttonVariant: 'warning',
    cancelLabel: 'Cancel',
    confirmLabel: 'Yes, proceed',
    icon: 'fas fa-triangle-exclamation',
    iconBackgroundColor: warning[25],
    iconColor: warning[100],
    message: 'This action cannot be undone. Are you sure?',
    title: 'Warning',
  },
} as const;
