interface SelectOption {
	value: string;
	label: string;
}

export const FONTS: SelectOption[] = [
	{ value: 'Poppins', label: 'Poppins' },
	{ value: 'Insanibu', label: 'Insanibu' },
	{ value: 'MINI_Serif', label: 'MINI_Serif' },
	{ value: 'CHEESEPIZZA', label: 'CHEESEPIZZA' },
	{ value: 'BMW', label: 'BMW' },
	{ value: 'Abrakatebra', label: 'Abrakatebra' },
	{ value: 'Aramisi', label: 'Aramisi' },
	{ value: 'Facebook', label: 'Facebook' },
	{ value: 'Merriweather', label: 'Merriweather' },
	{ value: 'MINI_Sans', label: 'MINI_Sans' },
	{ value: 'Arvo', label: 'Arvo' },
	{ value: 'Dolce_Vita', label: 'Dolce_Vita' },
	{ value: 'Spectral', label: 'Spectral' },
	{ value: 'Twitter', label: 'Twitter' },
	{ value: 'CaviarDreams', label: 'CaviarDreams' },
	{ value: 'Freestyle_Script', label: 'Freestyle_Script' },
	{ value: 'Roboto', label: 'Roboto' },
	{ value: 'Cardo', label: 'Cardo' },
	{ value: 'Oswald', label: 'Oswald' },
	{ value: 'Nunito', label: 'Nunito' },
	{ value: 'Oxygen', label: 'Oxygen' },
	{ value: 'arial', label: 'arial' },
	{ value: 'Lora', label: 'Lora' },
	{ value: 'Montserrat', label: 'Montserrat' },
	{ value: 'College_Block', label: 'College_Block' },
	{ value: 'Karla', label: 'Karla' },
	{ value: 'Raleway', label: 'Raleway' },
	{ value: 'Rubik', label: 'Rubik' },
	{ value: 'Underground', label: 'Underground' },
	{ value: 'SS_Nickson_One', label: 'SS_Nickson_One' },
	{ value: 'Instagram', label: 'Instagram' },
	{ value: 'Cormorant', label: 'Cormorant' },
	{ value: 'Hamburger_Heaven', label: 'Hamburger_Heaven' },
	{ value: 'Coquette_Regular', label: 'Coquette_Regular' },
	{ value: 'Lato', label: 'Lato' },
];

export const FONT_SIZES: SelectOption[] = [
	{ value: '5', label: '5' },
	{ value: '5.5', label: '5.5' },
	{ value: '6.5', label: '6.5' },
	{ value: '7.5', label: '7.5' },
	{ value: '8', label: '8' },
	{ value: '9', label: '9' },
	{ value: '10', label: '10' },
	{ value: '10.5', label: '10.5' },
	{ value: '11', label: '11' },
	{ value: '12', label: '12' },
	{ value: '14', label: '14' },
	{ value: '16', label: '16' },
	{ value: '18', label: '18' },
	{ value: '20', label: '20' },
	{ value: '22', label: '22' },
	{ value: '24', label: '24' },
	{ value: '26', label: '26' },
	{ value: '28', label: '28' },
	{ value: '36', label: '36' },
	{ value: '40', label: '40' },
	{ value: '44', label: '44' },
	{ value: '48', label: '48' },
	{ value: '58', label: '58' },
	{ value: '64', label: '64' },
	{ value: '72', label: '72' },
];

export default {
	FONTS,
	FONT_SIZES,
};
